Include.pcm_split.File "/common/pcm/split.conf"

Macro.playback.SplitPCM {
	Name "apple_t2_speakers"
	Direction Playback
	Format S24_LE
	Channels 2
	HWChannels 2
	HWChannelPos0 FL
	HWChannelPos1 FR
}

SectionVerb {
	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Internal Speakers"

	Value {
		PlaybackPriority 100
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "apple_t2_speakers"
		Direction Playback
		Device 0
		Channels 2
		HWChannels 2
		Channel0 0
		Channel1 1
		ChannelPos0 FL
		ChannelPos1 FR
	}
}

SectionDevice."Mic" {
	Comment "Internal Microphone"

	ConflictingDevice [
		"Headset"
	]

	Value {
		CapturePriority 300
		CaptureChannels 3
		CaptureRate 48000
		CapturePCM "hw:${CardId},1"
	}
}

SectionDevice."Headphones" {
	Comment "Headphones"

	ConflictingDevice [
		"Speaker"
	]

	Value {
		PlaybackPriority 300
		PlaybackChannels 2
		PlaybackPCM "hw:${CardId},2"
		JackControl "Codec Output Jack"
	}
}

SectionDevice."Headset" {
	Comment "Headset Microphone"

	ConflictingDevice [
		"Mic"
	]

	Value {
		CapturePriority 200
		CaptureChannels 1
		CapturePCM "hw:${CardId},3"
		JackControl "Codec Output Jack"
	}
}
