name: Generate new tag automatically

on:
  - push
jobs:
  auto_create_tag:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout Jammy Repo'
        uses: actions/checkout@v3
      - name: Get version
        id: generate_version
        run: |
          control=debian/control
          VERSION=$(grep "Version:" "$control" | cut -d ' ' -f 2)
          echo "ver=mic-v${VERSION}" >> $GITHUB_ENV
      - name: Check Tag Exists
        id: tag_exist
        run: |
          TAG_NAME=${{ env.ver }}  # Replace with the tag name you want to check
          if git ls-remote --exit-code --tags origin "refs/tags/$TAG_NAME" > /dev/null; then
            echo "Tag '$TAG_NAME' already exist"
             echo "result=1" >> $GITHUB_OUTPUT
          else
            echo "Tag '$TAG_NAME' does not exist"
            echo "result=0" >> $GITHUB_OUTPUT
          fi
      - name: Create Tag
        id: create_tag
        if: steps.tag_exist.outputs.result == 0
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${{ env.ver }}`,
                sha: context.sha
            })
