name: Generate new tag automatically

on:
  - push
jobs:
  auto_create_tag:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout Jammy Repo'
        uses: actions/checkout@v3
      - name: Get version
        id: generate_version
        run: |
          control=debian/control
          VERSION=$(grep "Version:" "$control" | cut -d ' ' -f 2)
          echo "ver=mic-v${VERSION}" >> $GITHUB_ENV
      - name: Create Tag
        id: create_tag
        uses: actions/github-script@v6
        with:
          script: |
            const {DIST_VERSION} = process.env
            github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${{ env.ver }}`,
                sha: context.sha
            })
