name: Generate new tag automatically

on:
  - push
jobs:
  auto_create_tag:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout Jammy Repo'
        uses: actions/checkout@v3
      - name: Get version
        run: |
          control=debian/control
          VERSION=$(grep "Version:" "$control" | cut -d ' ' -f 2)
          echo "ver=${VERSION}" >> $GITHUB_ENV
